In [1]:
import pandas as pd
import numpy as np

In [4]:
import os

os.listdir("/")

['tmp',
 'dev',
 'root',
 'usr',
 'bin',
 'var',
 'lib',
 'opt',
 'proc',
 'mnt',
 'media',
 'srv',
 'home',
 'sys',
 'boot',
 'run',
 'sbin',
 'lib64',
 'etc',
 'books_1.Best_Books_Ever.csv',
 'kaggle',
 '.dockerenv',
 'tools',
 'datalab',
 'content',
 'python-apt',
 'python-apt.tar.xz',
 'bin.usr-is-merged',
 'sbin.usr-is-merged',
 'lib.usr-is-merged']

In [6]:
df = pd.read_csv("/books_1.Best_Books_Ever.csv")

In [7]:
df.shape

(52478, 25)

In [8]:
df.columns.tolist()

['bookId',
 'title',
 'series',
 'author',
 'rating',
 'description',
 'language',
 'isbn',
 'genres',
 'characters',
 'bookFormat',
 'edition',
 'pages',
 'publisher',
 'publishDate',
 'firstPublishDate',
 'awards',
 'numRatings',
 'ratingsByStars',
 'likedPercent',
 'setting',
 'coverImg',
 'bbeScore',
 'bbeVotes',
 'price']

In [9]:
df.head()

,bookId,title,series,author,rating,description,language,isbn,genres,characters,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",...,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",...,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",...,01/28/13,[],2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",...,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,2.1

In [10]:
df.isnull().sum()

bookId                  0
title                   0
series              29008
author                  0
rating                  0
description          1338
language             3806
isbn                    0
genres                  0
characters              0
bookFormat           1473
edition             47523
pages                2347
publisher            3696
publishDate           880
firstPublishDate    21326
awards                  0
numRatings              0
ratingsByStars          0
likedPercent          622
setting                 0
coverImg              605
bbeScore                0
bbeVotes                0
price               14365
dtype: int64

In [20]:
selected_columns = [
    "bookId",
    "title",
    "author",
    "description",
    "genres",
    "rating",
    "coverImg",
    "language"
]

books = df[selected_columns].copy()

print("Before cleaning:")
print(books.shape)

print("\nMissing values:")
print(books.isnull().sum())

Before cleaning:
(52478, 8)

Missing values:
bookId            0
title             0
author            0
description    1338
genres            0
rating            0
coverImg        605
language       3806
dtype: int64

In [21]:
books.head()

,bookId,title,author,description,genres,rating,coverImg,language
0,2767052-the-hunger-games,The Hunger Games,Suzanne Collins,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,https://i.gr-assets.com/images/S/compressed.ph...,English
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",There is a door at the end of a silent corrido...,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",4.50,https://i.gr-assets.com/images/S/compressed.ph...,English
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",4.28,https://i.gr-assets.com/images/S/compressed.ph...,English
3,1885.Pride_and_Prejudice,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",Alternate cover edition of ISBN 9780679783268S...,"['Classics', 'Fiction', 'Romance', 'Historical...",4.26,https://i.gr-assets.com/images/S/compressed.ph...,English
4,41865.Twilight,Twilight,Stephenie Meyer,About three things I was absolutely positive.\...,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",3.60,https://i.gr-assets.com/images/S/compressed.ph...,English

In [22]:
books = books.dropna(subset=["description"]).copy()

print("After removing missing descriptions:")
print(books.shape)

print("\nMissing values:")
print(books.isnull().sum())

After removing missing descriptions:
(51140, 8)

Missing values:
bookId            0
title             0
author            0
description       0
genres            0
rating            0
coverImg        382
language       3473
dtype: int64

In [23]:
empty_descriptions = books["description"].str.strip().eq("").sum()

print("Empty descriptions:", empty_descriptions)

Empty descriptions: 0

In [24]:
print("Duplicate bookId:", books["bookId"].duplicated().sum())

Duplicate bookId: 52

In [25]:
duplicate_ids = books[
    books["bookId"].duplicated(keep=False)
].sort_values("bookId")

print("Number of rows involved:", len(duplicate_ids))

duplicate_ids[["bookId", "title", "author", "rating"]].head(20)

Number of rows involved: 104

,bookId,title,author,rating
37460,11737313-three-times-lucky,Three Times Lucky,Sheila Turnage,4.02
37406,11737313-three-times-lucky,Three Times Lucky,Sheila Turnage,4.02
37442,1258333.Cantarella_Volume_1,"Cantarella, Volume 1",You Higuri,3.81
37388,1258333.Cantarella_Volume_1,"Cantarella, Volume 1",You Higuri,3.81
37428,13571757-1,アオハライド 1,"Io Sakisaka, 咲坂伊緒",4.33
37482,13571757-1,アオハライド 1,"Io Sakisaka, 咲坂伊緒",4.33
37461,13614864-know-not-why,Know Not Why,Hannah Johnson (Goodreads Author),4.02
37407,13614864-know-not-why,Know Not Why,Hannah Johnson (Goodreads Author),4.02
37429,1481056.Gifts_and_Ministries_of_the_Holy_Spirit,Gifts and Ministries of the Holy Spirit,Lester Sumrall,4.44
37483,1481056.Gifts_and_Ministries_of_the_Holy_Spirit,Gifts and Ministries of the Holy Spirit,Lester Sumrall,4.44
37403,15733451-chairul-tanjung-si-anak-singkong,Chairul Tanjung Si Anak Singkong,Tjahja Gunawan Diredja,3.95
37457,15733451-chairul-tanjung-si-anak-singkong,Chairul Tanjung Si Anak Singkong,Tjahja Gunawan Diredja,3.95
37409,15741217-writing-scary-scenes,Writing Scary Scenes,Rayne Hall,4.06
37463,15741217-writing-scary-scenes,Writing Scary Scenes,Rayne Hall,4.06
37456,16058645-the-bookstore,The Bookstore,Deborah Meyler (Goodreads Author),3.08
37402,16058645-the-bookstore,The Bookstore,Deborah Meyler (Goodreads Author),3.08
37450,17337543-the-game-changer,The Game Changer,L.M. Trio (Goodreads Author),4.12
37396,17337543-the-game-changer,The Game Changer,L.M. Trio (Goodreads Author),4.12
37439,17786377,فضولية العلم,"Cyril Aydon, أحمد مغربي (ترجمة)",3.87
37385,17786377,فضولية العلم,"Cyril Aydon, أحمد مغربي (ترجمة)",3.87

In [26]:
duplicate_titles = books["title"].duplicated().sum()

print("Duplicate titles:", duplicate_titles)

Duplicate titles: 2513

In [27]:
title_counts = books["title"].value_counts()

print(title_counts[title_counts > 1].head(20))

title
Legacy            14
Broken            14
Selected Poems    11
Twisted           11
Forbidden         10
Haunted           10
Hunted            10
Forever            9
Torn               9
Sacrifice          9
Redemption         9
Burn               9
The Reckoning      8
Possession         8
Inferno            8
The Gift           8
The Promise        7
Perfect            7
Home               7
Reckless           7
Name: count, dtype: int64

In [28]:
print("Empty titles:",
      books["title"].str.strip().eq("").sum())

print("Empty authors:",
      books["author"].str.strip().eq("").sum())

print("Empty genres:",
      books["genres"].str.strip().eq("").sum())

print("Empty descriptions:",
      books["description"].str.strip().eq("").sum())

Empty titles: 0
Empty authors: 0
Empty genres: 0
Empty descriptions: 0

In [29]:
print("Duplicate bookIds:",
      books["bookId"].duplicated().sum())

Duplicate bookIds: 52

In [30]:
# Remove duplicate book IDs
books = books.drop_duplicates(
    subset="bookId",
    keep="first"
).reset_index(drop=True)

print("Dataset shape:", books.shape)
print("Duplicate bookIds:", books["bookId"].duplicated().sum())

Dataset shape: (51088, 8)
Duplicate bookIds: 0

In [31]:
print("Missing values:")
print(books.isnull().sum())

print("\nDuplicate bookIds:",
      books["bookId"].duplicated().sum())

print("\nEmpty titles:",
      books["title"].str.strip().eq("").sum())

print("Empty authors:",
      books["author"].str.strip().eq("").sum())

print("Empty genres:",
      books["genres"].str.strip().eq("").sum())

print("Empty descriptions:",
      books["description"].str.strip().eq("").sum())

Missing values:
bookId            0
title             0
author            0
description       0
genres            0
rating            0
coverImg        382
language       3468
dtype: int64

Duplicate bookIds: 0

Empty titles: 0
Empty authors: 0
Empty genres: 0
Empty descriptions: 0

In [32]:
books = books.reset_index(drop=True)

print(books.index)

RangeIndex(start=0, stop=51088, step=1)

In [33]:
import os

os.makedirs("/processed_data", exist_ok=True)

In [35]:
output_path = "/processed_data/books_processed.csv"

books.to_csv(output_path, index=False)

print(f"Saved processed dataset to: {output_path}")

Saved processed dataset to: /processed_data/books_processed.csv

In [36]:
processed_books = pd.read_csv(output_path)

print("Shape:", processed_books.shape)
print("\nColumns:")
print(processed_books.columns.tolist())
print("\nFirst 5 rows:")
display(processed_books.head())

Shape: (51088, 8)

Columns:
['bookId', 'title', 'author', 'description', 'genres', 'rating', 'coverImg', 'language']

First 5 rows:

,bookId,title,author,description,genres,rating,coverImg,language
0,2767052-the-hunger-games,The Hunger Games,Suzanne Collins,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,https://i.gr-assets.com/images/S/compressed.ph...,English
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",There is a door at the end of a silent corrido...,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",4.50,https://i.gr-assets.com/images/S/compressed.ph...,English
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",4.28,https://i.gr-assets.com/images/S/compressed.ph...,English
3,1885.Pride_and_Prejudice,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",Alternate cover edition of ISBN 9780679783268S...,"['Classics', 'Fiction', 'Romance', 'Historical...",4.26,https://i.gr-assets.com/images/S/compressed.ph...,English
4,41865.Twilight,Twilight,Stephenie Meyer,About three things I was absolutely positive.\...,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",3.60,https://i.gr-assets.com/images/S/compressed.ph...,English

In [37]:
import pandas as pd

books = pd.read_csv("/processed_data/books_processed.csv")

print(books.shape)
print(books.columns.tolist())

(51088, 8)
['bookId', 'title', 'author', 'description', 'genres', 'rating', 'coverImg', 'language']

In [38]:
nlp_books = books[
    [
        "bookId",
        "title",
        "author",
        "genres",
        "description"
    ]
].copy()

In [40]:
nlp_books.head()

,bookId,title,author,genres,description
0,2767052-the-hunger-games,The Hunger Games,Suzanne Collins,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)","['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",There is a door at the end of a silent corrido...
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,Harper Lee,"['Classics', 'Fiction', 'Historical Fiction', ...",The unforgettable novel of a childhood in a sl...
3,1885.Pride_and_Prejudice,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)","['Classics', 'Fiction', 'Romance', 'Historical...",Alternate cover edition of ISBN 9780679783268S...
4,41865.Twilight,Twilight,Stephenie Meyer,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",About three things I was absolutely positive.\...

In [39]:
nlp_books.shape

(51088, 5)

In [41]:
import ast

def clean_genres(genre_string):
    try:
        genres = ast.literal_eval(genre_string)
        return ", ".join(genres)
    except:
        return str(genre_string)


nlp_books["genres_clean"] = nlp_books["genres"].apply(clean_genres)

In [42]:
display(
    nlp_books[
        ["genres", "genres_clean"]
    ].head(10)
)

,genres,genres_clean
0,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","Young Adult, Fiction, Dystopia, Fantasy, Scien..."
1,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","Fantasy, Young Adult, Fiction, Magic, Children..."
2,"['Classics', 'Fiction', 'Historical Fiction', ...","Classics, Fiction, Historical Fiction, School,..."
3,"['Classics', 'Fiction', 'Romance', 'Historical...","Classics, Fiction, Romance, Historical Fiction..."
4,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","Young Adult, Fantasy, Romance, Vampires, Ficti..."
5,"['Historical Fiction', 'Fiction', 'Young Adult...","Historical Fiction, Fiction, Young Adult, Hist..."
6,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...","Classics, Fiction, Dystopia, Fantasy, Literatu..."
7,"['Fantasy', 'Classics', 'Fiction', 'Young Adul...","Fantasy, Classics, Fiction, Young Adult, Child..."
8,"['Fantasy', 'Fiction', 'Classics', 'Adventure'...","Fantasy, Fiction, Classics, Adventure, Science..."
9,"['Classics', 'Historical Fiction', 'Fiction', ...","Classics, Historical Fiction, Fiction, Romance..."

In [43]:
nlp_books["text"] = (
    "Title: " + nlp_books["title"].astype(str) +
    ". Author: " + nlp_books["author"].astype(str) +
    ". Genres: " + nlp_books["genres_clean"].astype(str) +
    ". Description: " + nlp_books["description"].astype(str)
)

In [44]:
print(nlp_books["text"].iloc[0])

Title: The Hunger Games. Author: Suzanne Collins. Genres: Young Adult, Fiction, Dystopia, Fantasy, Science Fiction, Romance, Adventure, Teen, Post Apocalyptic, Action. Description: WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.

In [45]:
for i in range(3):
    print(f"\n--- Book {i+1} ---")
    print(nlp_books["text"].iloc[i])

--- Book 1 ---
Title: The Hunger Games. Author: Suzanne Collins. Genres: Young Adult, Fiction, Dystopia, Fantasy, Science Fiction, Romance, Adventure, Teen, Post Apocalyptic, Action. Description: WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.

--- Book 2 ---
Title: Harry Potter and the Order of the Phoenix. Author: J.K. Rowling, Mary GrandPré (Illustrator). Genres: Fantasy, Young Adult, Fiction, Magic, Childrens, Adventure, Audiobook, Middle Grade, Classics, Science Fiction Fantasy. Description: There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them all.

--- Book 3 ---
Title: To Kill a Mockingbird. Author: Harper Lee. Genres: Classics, Fiction, Historical Fiction, School, Literature, Young Adult, Historical, Novels, Read For School, High School. Description: The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.

In [46]:
display(
    nlp_books[
        ["title", "genres_clean", "description", "text"]
    ].head(3)
)

,title,genres_clean,description,text
0,The Hunger Games,"Young Adult, Fiction, Dystopia, Fantasy, Scien...",WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,Title: The Hunger Games. Author: Suzanne Colli...
1,Harry Potter and the Order of the Phoenix,"Fantasy, Young Adult, Fiction, Magic, Children...",There is a door at the end of a silent corrido...,Title: Harry Potter and the Order of the Phoen...
2,To Kill a Mockingbird,"Classics, Fiction, Historical Fiction, School,...",The unforgettable novel of a childhood in a sl...,Title: To Kill a Mockingbird. Author: Harper L...

In [47]:
print(nlp_books["text"].str.len().describe())

count    51088.000000
mean      1048.664657
std        554.351956
min         65.000000
25%        704.000000
50%        982.000000
75%       1281.000000
max      24837.000000
Name: text, dtype: float64

In [48]:
# Make sure text is string
nlp_books["text"] = nlp_books["text"].astype(str)

# Replace newlines, tabs and repeated whitespace
nlp_books["text"] = (
    nlp_books["text"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [49]:
print("Empty text:",
      nlp_books["text"].str.len().eq(0).sum())

print("Missing text:",
      nlp_books["text"].isnull().sum())

Empty text: 0
Missing text: 0

In [50]:
for i in range(3):
    print(f"\n--- Book {i+1} ---")
    print(nlp_books["text"].iloc[i])

--- Book 1 ---
Title: The Hunger Games. Author: Suzanne Collins. Genres: Young Adult, Fiction, Dystopia, Fantasy, Science Fiction, Romance, Adventure, Teen, Post Apocalyptic, Action. Description: WINNING MEANS FAME AND FORTUNE.LOSING MEANS CERTAIN DEATH.THE HUNGER GAMES HAVE BEGUN. . . .In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and once girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.

--- Book 2 ---
Title: Harry Potter and the Order of the Phoenix. Author: J.K. Rowling, Mary GrandPré (Illustrator). Genres: Fantasy, Young Adult, Fiction, Magic, Childrens, Adventure, Audiobook, Middle Grade, Classics, Science Fiction Fantasy. Description: There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named - a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them all.

--- Book 3 ---
Title: To Kill a Mockingbird. Author: Harper Lee. Genres: Classics, Fiction, Historical Fiction, School, Literature, Young Adult, Historical, Novels, Read For School, High School. Description: The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.

In [51]:
nlp_final = nlp_books[
    [
        "bookId",
        "title",
        "author",
        "genres",
        "description",
        "text"
    ]
].copy()

In [52]:
print("Shape:", nlp_final.shape)
print("\nColumns:")
print(nlp_final.columns.tolist())

Shape: (51088, 6)

Columns:
['bookId', 'title', 'author', 'genres', 'description', 'text']

In [53]:
nlp_final.head()

,bookId,title,author,genres,description,text
0,2767052-the-hunger-games,The Hunger Games,Suzanne Collins,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,Title: The Hunger Games. Author: Suzanne Colli...
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)","['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",There is a door at the end of a silent corrido...,Title: Harry Potter and the Order of the Phoen...
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,Harper Lee,"['Classics', 'Fiction', 'Historical Fiction', ...",The unforgettable novel of a childhood in a sl...,Title: To Kill a Mockingbird. Author: Harper L...
3,1885.Pride_and_Prejudice,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)","['Classics', 'Fiction', 'Romance', 'Historical...",Alternate cover edition of ISBN 9780679783268S...,Title: Pride and Prejudice. Author: Jane Auste...
4,41865.Twilight,Twilight,Stephenie Meyer,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",About three things I was absolutely positive.\...,Title: Twilight. Author: Stephenie Meyer. Genr...

In [54]:
import os

os.makedirs("/nlp_data", exist_ok=True)

nlp_output = "/nlp_data/books_nlp.csv"

nlp_final.to_csv(nlp_output, index=False)

print(f"NLP dataset saved to: {nlp_output}")

NLP dataset saved to: /nlp_data/books_nlp.csv

In [55]:
check = pd.read_csv(nlp_output)

print("Shape:", check.shape)
print(check.head(2))

Shape: (51088, 6)
                                        bookId  \
0                     2767052-the-hunger-games
1  2.Harry_Potter_and_the_Order_of_the_Phoenix

                                       title  \
0                           The Hunger Games
1  Harry Potter and the Order of the Phoenix

                                      author  \
0                            Suzanne Collins
1  J.K. Rowling, Mary GrandPré (Illustrator)

                                              genres  \
0  ['Young Adult', 'Fiction', 'Dystopia', 'Fantas...
1  ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...

                                         description  \
0  WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...
1  There is a door at the end of a silent corrido...

                                                text
0  Title: The Hunger Games. Author: Suzanne Colli...
1  Title: Harry Potter and the Order of the Phoen...

In [56]:
!pip install -q sentence-transformers

In [57]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [58]:
print("Model:", model)
print("Max sequence length:", model.max_seq_length)

Model: SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)
Max sequence length: 256